"""
Multi-agent protocol parsing and role management.
Handles parsing of <agent=RoleName> tags and role-based action extraction.
"""

import re
from typing import List, Tuple, Optional, Dict
from enum import Enum
from dataclasses import dataclass


class AgentRole(str, Enum):
    """Agent role types."""
    PLANNER = "Planner"
    EXPLORER = "Explorer"
    SYNTHESIZER = "Synthesizer"


@dataclass
class AgentSegment:
    """Represents a segment generated by a specific agent."""
    role: str
    content: str
    start_pos: int
    end_pos: int
    search_queries: List[str] = None
    has_answer: bool = False
    
    def __post_init__(self):
        if self.search_queries is None:
            self.search_queries = []


class MultiAgentProtocol:
    """
    Parser for multi-agent protocol tags.
    Extends single-agent protocol with <agent=RoleName> tags.
    """
    
    # Patterns for parsing
    AGENT_PATTERN = re.compile(r'<agent=([^>]+)>(.*?)</agent>', re.DOTALL)
    SEARCH_PATTERN = re.compile(r'<search>(.*?)</search>', re.DOTALL)
    ANSWER_PATTERN = re.compile(r'<answer>(.*?)</answer>', re.DOTALL)
    INFORMATION_PATTERN = re.compile(r'<information(?:\s+agent=([^>]+))?>(.*?)</information>', re.DOTALL)
    
    @staticmethod
    def parse_agent_segment(text: str) -> Optional[Tuple[str, str]]:
        """
        Parse an agent segment from text.
        
        Args:
            text: Text containing <agent=RoleName>...</agent>
            
        Returns:
            Tuple of (role_name, content) or None if not found
        """
        match = MultiAgentProtocol.AGENT_PATTERN.search(text)
        if match:
            role = match.group(1).strip()
            content = match.group(2).strip()
            return role, content
        return None
    
    @staticmethod
    def extract_search_queries(text: str) -> List[str]:
        """
        Extract all search queries from text.
        
        Args:
            text: Text containing <search>...</search> tags
            
        Returns:
            List of search query strings
        """
        matches = MultiAgentProtocol.SEARCH_PATTERN.findall(text)
        return [q.strip() for q in matches]
    
    @staticmethod
    def extract_answer(text: str) -> Optional[str]:
        """
        Extract answer from text.
        
        Args:
            text: Text containing <answer>...</answer>
            
        Returns:
            Answer string or None
        """
        match = MultiAgentProtocol.ANSWER_PATTERN.search(text)
        if match:
            return match.group(1).strip()
        return None
    
    @staticmethod
    def parse_information_block(text: str) -> Optional[Tuple[Optional[str], str]]:
        """
        Parse information block with optional agent attribute.
        
        Args:
            text: Text containing <information agent=...>...</information>
            
        Returns:
            Tuple of (agent_name, content) or None if not found
        """
        match = MultiAgentProtocol.INFORMATION_PATTERN.search(text)
        if match:
            agent = match.group(1).strip() if match.group(1) else None
            content = match.group(2).strip()
            return agent, content
        return None
    
    @staticmethod
    def wrap_agent_segment(role: str, content: str) -> str:
        """
        Wrap content in agent tags.
        
        Args:
            role: Agent role name
            content: Content to wrap
            
        Returns:
            Wrapped string
        """
        return f"<agent={role}>\n{content}\n</agent>"
    
    @staticmethod
    def wrap_information_block(content: str, agent_name: Optional[str] = None) -> str:
        """
        Wrap content in information tags with optional agent attribute.
        
        Args:
            content: Information content
            agent_name: Optional agent name that triggered this search
            
        Returns:
            Wrapped string
        """
        if agent_name:
            return f'\n\n<information agent={agent_name}>{content.strip()}</information>\n\n'
        else:
            return f'\n\n<information>{content.strip()}</information>\n\n'
    
    @staticmethod
    def parse_segment(text: str, role: str) -> AgentSegment:
        """
        Parse a complete agent segment with all its components.
        
        Args:
            text: Full segment text
            role: Expected role name
            
        Returns:
            AgentSegment object
        """
        # Extract agent content
        agent_match = MultiAgentProtocol.AGENT_PATTERN.search(text)
        if agent_match:
            segment_content = agent_match.group(2)
        else:
            segment_content = text
        
        # Extract search queries
        search_queries = MultiAgentProtocol.extract_search_queries(segment_content)
        
        # Check for answer
        answer = MultiAgentProtocol.extract_answer(segment_content)
        has_answer = answer is not None
        
        return AgentSegment(
            role=role,
            content=segment_content,
            start_pos=0,  # Will be set by caller if needed
            end_pos=len(text),
            search_queries=search_queries,
            has_answer=has_answer
        )

